### PR TITLE
chore : upload Encryption adding KEY using Router

### PR DESCRIPTION
**Pull request by aimanzi**
encryption server using .env(for the KEY) an router
to start the server insert in the termminal :  npm run start-enc1

### CODE REVIEW

**Comment by aimanzi** [comment]
to post use postman to the appropriate port

**Comment by EliasSalom** [comment]
there is conflicts that must be resolved

**Comment by aimanzi** [comment]
conflicts solved

**Review by EliasSalom — APPROVED** [review]
LGTM

**Pull request merged**
