### PR TITLE
chore:adding fetch-API-movie homework

### PR DESCRIPTION
**Pull request by aimanzi**
fetching for movies Api , searching by movie name and type.
we can add another searching option .

### CODE REVIEW

**Comment by aimanzi** [comment]
Hi elias,
by mistake i push the homework in bransh that already mearged , i had set delete branch after mearging.so you have to choose the following debloy link .
https://github.com/Fullstack-Alfanar/Aiman-React-Homeworks/deployments/activity_log?environment=movie-api-fetching-display.

**Review by EliasSalom — APPROVED** [review]
LGTM

**Comment by EliasSalom** [comment]
you have some conflicts please fix them

**Comment by aimanzi** [comment]
Conflict in the branch it self ?

Sent from my iPhone

On 26 Jul 2022, at 13:41, elias salom ***@***.***> wrote:

﻿

you have some conflicts please fix them

**Comment by EliasSalom** [comment]
please check your pull request

**Comment by aimanzi** [comment]
sorry i forget that , problem solved

**Review by EliasSalom — APPROVED** [review]
LGTM

**Pull request merged**
